export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS';
export const PRODUCT_REQUEST_FAILED = 'PRODUCT_REQUEST_FAILED';

export const PRODUCT_END_REACHED = 'PRODUCT_END_REACHED';
